sudo: required

language: python

services:
  - docker

before_install:
  - pip install behave
  - docker build -t sftech/squid .
  - docker run -d -p 3128:3128 sftech/squid
  - docker ps -a

script: behave

